version: '2'

services:
  haproxy:
    build: ./haproxy/.
    ports:
     - '80:8080'
     - '8404:8404'
  nginx1:
    build: ./nginx1/.

  nginx2:
    build: ./nginx2/.

  nginx3:
    build: ./nginx3/.

  nginx4:
    build: ./nginx4/.

  nginx5:
    build: ./nginx5/.