name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: haproxy:2.3.1-alpine

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose up -d
          else
            docker build . --file Dockerfile
          fi
